// src/lib/projects/projects_list.svelte
<script lang='ts'>
  import { getContext, onMount } from 'svelte';
  import { ProjectsController } from '$lib/projects/projects_controller';
  import type { Project } from '$lib/projects/projects_controller';
  import { ProjectsControllerKey } from '$lib/di';

  const projectsController = getContext<ProjectsController>(ProjectsControllerKey);
  let projects: Project[] | undefined;

  onMount(async () => {
    projects = await projectsController.fetchProjects();
  });

  function handleChooseDirectory() {
    projectsController.chooseDir();
  }

  async function handleActivateProject(project: Project) {
    await projectsController.activate(project);
    projects = await projectsController.fetchProjects();
  }
</script>

<div>
  <button on:click={handleChooseDirectory}>Choose projects directory</button>

  <table>
    {#each projects as project}
      <tr>
        <td class='title' class:active={project.isActive}>
          { project.name }
        </td>
        <td>
          <button on:click={() => handleActivateProject(project)}>activate</button>
        </td>
      </tr>
    {/each}
  </table>
</div>

<style>
  .title {
    text-align: left;
  }

  .active {
    font-weight: bold;
  }
</style>

// src2/features/projects/projects_list.tsx
import React from 'react';
import { type Project, ProjectsController } from './projects_controller';
import { ProjectsRepo } from './projects_repo';
import { Database } from '../../lib/database';
import { Button, Stack, Table, Text } from '@mantine/core';

const db = new Database();
const projectsRepo = new ProjectsRepo(db);
const projectsController = new ProjectsController(projectsRepo);

export const ProjectsList = () => {
  const [projects, setProjects] = React.useState<Project[]>([]);

  React.useEffect(() => {
    projectsController.fetchProjects().then((projects) => {
      if (!projects) return;
      setProjects(projects);
    });
  }, []);

  const onActivateProject = async (project: Project) => {
    await projectsController.activate(project);
    const updatedProjects = await projectsController.fetchProjects();
    if (updatedProjects) {
      setProjects(updatedProjects);
    }
  };

  const onChooseDirectory = () => {
    projectsController.chooseDir();
  };

  return (
    <Stack align="start">
      <Button onClick={onChooseDirectory}>Choose projects directory</Button>
      <Table withTableBorder withColumnBorders>
        <Table.Tbody>
          {projects.map((project) => (
            <Table.Tr key={project.name}>
              <Table.Td>
                <Text fw={project.isActive ? 'bold' : 'normal'}>
                  {project.name}
                </Text>
              </Table.Td>
              <Table.Td>
                <Button onClick={() => onActivateProject(project)}>
                  Activate
                </Button>
              </Table.Td>
            </Table.Tr>
          ))}
        </Table.Tbody>
      </Table>
    </Stack>
  );
};
