// src/routes/timeline/video_clip.svelte
<script lang='ts'>
  import type { VideoTimelineClip } from '$lib/video/video_timeline.svelte';

  export let timelineClip: VideoTimelineClip;
  export let maxDuration: number;
  export let isSelected: boolean;
  export let onSelect: (clip: VideoTimelineClip) => void;

  $: width = timelineClip.duration / maxDuration * 100;

  function handleClick() {
    onSelect(timelineClip);
  }
</script>

<div
  class='container'
  class:selected={isSelected}
  on:click={handleClick}
  style='width: {width}%'
>
  {timelineClip.videoId}
</div>

<style>
  .container {
    height: 100%;
    overflow: hidden;
    box-sizing: border-box;
  }

  .container:nth-child(odd) {
    background: #eee;
  }

  .selected {
    border: 1px solid blue;
  }
</style>

// src2/pages/timeline/video_track/video_clip.tsx
import type { VideoTimelineClip } from '../../../features/video_timeline/video_timeline_selectors';

import classes from './video_clip.module.css';

export const VideoClip = ({
  timelineClip,
  isSelected,
  onSelect,
  maxDuration,
}: {
  timelineClip: VideoTimelineClip;
  isSelected: boolean;
  onSelect: (clip: VideoTimelineClip) => void;
  maxDuration: number;
}) => {
  const width = (timelineClip.duration / maxDuration) * 100;

  return (
    <div
      className={classes.root}
      data-selected={isSelected}
      onClick={() => onSelect(timelineClip)}
      style={{ width: `${width}%` }}
    >
      {timelineClip.videoId}
    </div>
  );
};
