// src/lib/manifest/manifest_save_button.svelte
<script lang='ts'>
  import { ManifestWriter } from '$lib/manifest/manifest_writer';
  import { Manifest } from '$lib/manifest/manifest.svelte';

  const manifestWriter = new ManifestWriter();

  export let manifest: Manifest;

  function handleSave() {
    void manifestWriter.writeWithFilePicker(manifest);
  }
</script>

<button on:click={handleSave}>save manifest</button>

// src/features/manifest/manifest_save_button.tsx
import { Button } from '@mantine/core';
import { useManifest } from './use_manifest';

export const ManifestSaveButton = () => {
  const { manifestStore, manifestWriter } = useManifest();

  const onClick = () => {
    void manifestWriter.writeWithFilePicker(manifestStore);
  };

  return <Button onClick={onClick}>save manifest</Button>;
};
