// src/routes/timeline/+page.svelte
<script lang='ts'>
  import VideoTrack from './video_track.svelte';
  import { getContext, onMount } from 'svelte';
  import { fetchManifest } from '$lib/manifest';
  import { VideoResolver } from '$lib/video_resolver';
  import { AudioResolverKey, VideoResolverKey } from '$lib/di';
  import { VideoTimeline } from '$lib/video_timeline';
  import type { VideoTimelineClip } from '$lib/video_timeline';
  import AudioTrack from './audio_track.svelte';
  import { AudioResolver } from '$lib/audio_resolver';
  import { AudioTimeline } from '$lib/audio_timeline';
  import type { AudioTimelineClip } from '$lib/audio_timeline';
  import { toMinutesString } from '$lib/time_utils.js';
  import { AudioProducer } from '$lib/audio_producer';
  import PlayheadTrack from './playhead_track.svelte';

  const videoResolver = getContext<VideoResolver>(VideoResolverKey);
  const audioResolver = getContext<AudioResolver>(AudioResolverKey);

  let audioProducer: AudioProducer;

  let videoTimelineClips: VideoTimelineClip[] = [];
  let audioTimelineClips: AudioTimelineClip[] = [];
  let videoDuration: number = 0;
  let audioDuration: number = 0;
  let maxDuration: number = 0;
  let time: number;

  onMount(async () => {
    const setId = '03_jrugz';
    const manifest = await fetchManifest(setId);
    console.log({ manifest });

    await videoResolver.loadMetadata(manifest.videoTrack.clips);
    const videoTimeline = new VideoTimeline(manifest, videoResolver);

    await audioResolver.loadMetadata(manifest.audioTrack.clips);
    const audioTimeline = new AudioTimeline(manifest, audioResolver);

    audioProducer = new AudioProducer(audioTimeline, audioResolver);

    videoTimelineClips = videoTimeline.getTimelineClips();
    audioTimelineClips = audioTimeline.getTimelineClips();

    videoDuration = videoTimeline.getTotalDuration();
    audioDuration = audioTimeline.getTotalDuration();
    maxDuration = Math.max(videoDuration, audioDuration);
  });

  function handlePlay() {
    audioProducer.play();
  }

  function handlePlayheadSeek(playheadTime: number) {
    time = playheadTime;
  }
</script>

<div>
  Video duration: {toMinutesString(videoDuration)} <br />
  Audio duration: {toMinutesString(audioDuration)} <br />
  Max duration: {toMinutesString(maxDuration)} <br />
  <hr />
  <button on:click={handlePlay}>play</button>
  <hr />
  <div class='tracks'>
    <PlayheadTrack time={time} maxDuration={maxDuration} onSeek={handlePlayheadSeek} />
    <VideoTrack timelineClips={videoTimelineClips} maxDuration={maxDuration} />
    <AudioTrack timelineClips={audioTimelineClips} maxDuration={maxDuration} />
  </div>
</div>

<style>
  .tracks {
    width: 100%;
  }
</style>

// src/pages/timeline/timeline/timeline.tsx
import { useAudioTimeline } from '../../../features/audio_timeline/use_audio_timeline';
import { useVideoTimeline } from '../../../features/video_timeline/use_video_timeline';
import { AudioTrack } from '../audio_track/audio_track';
import { PlayheadTrack } from '../playhead_track/playhead_track';
import { VideoTrack } from '../video_track/video_track';
import { useTimelineClock } from '../use_timeline_clock';

export const Timeline = ({
  onPlayheadSeek,
}: {
  onPlayheadSeek: (newTime: number) => void;
}) => {
  const { videoTimeline } = useVideoTimeline();
  const { audioTimeline } = useAudioTimeline();
  const { playheadTime, timelineClock } = useTimelineClock();

  const videoDuration = videoTimeline.getTotalDuration();
  const audioDuration = audioTimeline.getTotalDuration();
  const maxDuration = Math.max(videoDuration, audioDuration);

  const onSeek = (newTime: number) => {
    timelineClock.seek(newTime);
    onPlayheadSeek(newTime);
  };

  return (
    <div>
      <PlayheadTrack
        time={playheadTime}
        maxDuration={maxDuration}
        onSeek={onSeek}
      />
      <VideoTrack maxDuration={maxDuration} />
      <AudioTrack maxDuration={maxDuration} />
    </div>
  );
};
