// src/pages/timeline/audio_clip_details/audio_clip_details.tsx
import { NumberInput, Table } from '@mantine/core';
import { toMinutesString } from '../../../lib/time_utils';
import { useManifest } from '../../../features/manifest/use_manifest';
import type { AudioTimelineClip } from '../../../features/audio_timeline/audio_timeline_selectors';

const Tr = Table.Tr;
const Th = Table.Th;
const Td = Table.Td;

export const AudioClipDetails: React.FC<{
  timelineClip: AudioTimelineClip;
  playheadTime: number;
}> = ({ timelineClip, playheadTime }) => {
  const { manifestStore } = useManifest();

  const onTrimEndChange = (value: string | number) => {
    if (typeof value === 'string') {
      return;
    }
    manifestStore.audioTrackStore
      .getClipStore(timelineClip.audioId)
      .setTrimEnd(value);
  };

  return (
    <Table variant="vertical">
      <Table.Tbody>
        <Tr>
          <Th>id</Th>
          <Td>{timelineClip.audioId}</Td>
        </Tr>
        <Tr>
          <Th>index</Th>
          <Td>{timelineClip.index}</Td>
        </Tr>
        <Tr>
          <Th>last</Th>
          <Td>{timelineClip.isLast ? 'Yes' : 'No'}</Td>
        </Tr>
        <Tr>
          <Td colSpan={2}></Td>
        </Tr>
        <Tr>
          <Th>start</Th>
          <Td>{toMinutesString(timelineClip.start)}</Td>
        </Tr>
        <Tr>
          <Th>end</Th>
          <Td>{toMinutesString(timelineClip.end)}</Td>
        </Tr>
        <Tr>
          <Th>duration</Th>
          <Td>{toMinutesString(timelineClip.duration)}</Td>
        </Tr>
        <Tr>
          <Th>source duration</Th>
          <Td>{toMinutesString(timelineClip.sourceDuration)}</Td>
        </Tr>
        <Tr>
          <Th>trimmed duration</Th>
          <Td>{toMinutesString(timelineClip.trimmedDuration)}</Td>
        </Tr>
        <Tr>
          <Td colSpan={2}></Td>
        </Tr>
        <Tr>
          <Th>time left</Th>
          <Td>
            {playheadTime > timelineClip.end ||
            playheadTime < timelineClip.start
              ? '-'
              : toMinutesString(timelineClip.end - playheadTime, true)}
          </Td>
        </Tr>
        <Tr>
          <Td colSpan={2}></Td>
        </Tr>
        <Tr>
          <Th>trim end</Th>
          <Td>
            <NumberInput
              value={timelineClip.clip.trimEnd}
              onChange={onTrimEndChange}
            />
          </Td>
        </Tr>
      </Table.Tbody>
    </Table>
  );
};

// src/routes/timeline/audio_clip_details.svelte
<script lang="ts">
  import { toMinutesString } from '$lib/time_utils.js';
  import type { Manifest } from '$lib/manifest/manifest.svelte';
  import type { AudioTimelineClip } from '$lib/audio/audio_timeline.svelte';

  export let manifest: Manifest;
  export let timelineClip: AudioTimelineClip;
  export let playheadTime: number;

  function handleTrimEndChange(e: Event & { currentTarget: HTMLInputElement }) {
    manifest.audioTrack.getClip(timelineClip.audioId).trimEnd = Number(
      e.currentTarget.value,
    );
  }
</script>

<div>
  <table>
    <tbody>
      <tr>
        <th class="head">id</th>
        <td class="cell">{timelineClip.videoId}</td>
      </tr>
      <tr>
        <th class="head">index</th>
        <td class="cell">{timelineClip.index}</td>
      </tr>
      <tr>
        <th class="head">last</th>
        <td class="cell">{timelineClip.isLast}</td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
      <tr>
        <th class="head">start</th>
        <td class="cell">{toMinutesString(timelineClip.start)}</td>
      </tr>
      <tr>
        <th class="head">end</th>
        <td class="cell">{toMinutesString(timelineClip.end)}</td>
      </tr>
      <tr>
        <th class="head">duration</th>
        <td class="cell">{toMinutesString(timelineClip.duration)}</td>
      </tr>
      <tr>
        <th class="head">source duration</th>
        <td class="cell">{toMinutesString(timelineClip.sourceDuration)}</td>
      </tr>
      <tr>
        <th class="head">trimmed duration</th>
        <td class="cell">{toMinutesString(timelineClip.trimmedDuration)}</td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
      <tr>
        <th class="head">time left</th>
        <td class="cell">
          {playheadTime > timelineClip.end || playheadTime < timelineClip.start
            ? '-'
            : toMinutesString(timelineClip.end - playheadTime, true)}
        </td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
      <tr>
        <th class="head">trim end</th>
        <td class="cell">
          <input
            type="number"
            on:change={handleTrimEndChange}
            value={timelineClip.clip.trimEnd}
          />
        </td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
    </tbody>
  </table>
</div>

<style>
  .head {
    text-align: right;
  }

  .cell {
    text-align: left;
  }

  .divider {
    padding: 0;
    height: 3px;
    background: #eee;
    border: 0;
  }
</style>
