// src/pages/timeline/video_clip_details/video_clip_details.tsx
import { Button, Group, NumberInput, Table } from '@mantine/core';
import type { VideoTimelineClip } from '../../../features/video_timeline/video_timeline_selectors';
import { toMinutesString } from '../../../lib/time_utils';
import { useManifest } from '../../../features/manifest/use_manifest';
import { OffsetPicker } from '../../../ui/offset_picker/offset_picker';

const Tr = Table.Tr;
const Th = Table.Th;
const Td = Table.Td;

export const VideoClipDetails: React.FC<{
  timelineClip: VideoTimelineClip;
  playheadTime: number;
}> = ({ timelineClip, playheadTime }) => {
  const { manifestStore } = useManifest();

  const onRateChange = (value: string | number) => {
    if (typeof value === 'string') {
      return;
    }
    manifestStore.videoTrackStore
      .getClipStore(timelineClip.videoId)
      .setRate(value);
  };

  const onCustomDurationChange = (value: string | number) => {
    if (typeof value === 'string') {
      return;
    }
    manifestStore.videoTrackStore
      .getClipStore(timelineClip.videoId)
      .setCustomDuration(value);
  };

  const onOffsetXChange = (value: string | number | undefined) => {
    manifestStore.videoTrackStore
      .getClipStore(timelineClip.videoId)
      .setOffsetX(value);
  };

  const onOffsetYChange = (value: string | number | undefined) => {
    manifestStore.videoTrackStore
      .getClipStore(timelineClip.videoId)
      .setOffsetY(value);
  };

  const onMoveLeft = () => {
    manifestStore.videoTrackStore.moveLeft(timelineClip.videoId);
  };

  const onMoveRight = () => {
    manifestStore.videoTrackStore.moveRight(timelineClip.videoId);
  };

  return (
    <Table variant="vertical">
      <Table.Tbody>
        <Tr>
          <Th>id</Th>
          <Td>{timelineClip.videoId}</Td>
        </Tr>
        <Tr>
          <Th>index</Th>
          <Td>{timelineClip.index}</Td>
        </Tr>
        <Tr>
          <Th>last</Th>
          <Td>{timelineClip.isLast ? 'Yes' : 'No'}</Td>
        </Tr>
        <Tr>
          <Td colSpan={2}></Td>
        </Tr>
        <Tr>
          <Th>start</Th>
          <Td>{toMinutesString(timelineClip.start)}</Td>
        </Tr>
        <Tr>
          <Th>end</Th>
          <Td>{toMinutesString(timelineClip.end)}</Td>
        </Tr>
        <Tr>
          <Th>custom duration</Th>
          <Td>
            <NumberInput
              value={timelineClip.customDuration}
              onChange={onCustomDurationChange}
            />
          </Td>
        </Tr>
        <Tr>
          <Th>duration</Th>
          <Td>{toMinutesString(timelineClip.duration)}</Td>
        </Tr>
        <Tr>
          <Th>rated duration</Th>
          <Td>{toMinutesString(timelineClip.ratedDuration)}</Td>
        </Tr>
        <Tr>
          <Th>rate</Th>
          <Td>
            <NumberInput
              min={0.1}
              step={0.1}
              max={10}
              value={timelineClip.rate}
              onChange={onRateChange}
            />
          </Td>
        </Tr>
        <Tr>
          <Th>file duration</Th>
          <Td>{toMinutesString(timelineClip.fileDuration)}</Td>
        </Tr>
        <Tr>
          <Th>trimmed duration</Th>
          <Td>{toMinutesString(timelineClip.trimmedDuration)}</Td>
        </Tr>
        <Tr>
          <Td colSpan={2}></Td>
        </Tr>
        <Tr>
          <Th>time left</Th>
          <Td>
            {playheadTime > timelineClip.end ||
            playheadTime < timelineClip.start
              ? '-'
              : toMinutesString(timelineClip.end - playheadTime, true)}
          </Td>
        </Tr>
        <Tr>
          <Td colSpan={2}></Td>
        </Tr>
        <Tr>
          <Th>offsetX</Th>
          <Td>
            <OffsetPicker
              value={timelineClip.clip.offsetX}
              onChange={onOffsetXChange}
              extraOptions={['left', 'center', 'right']}
            />
          </Td>
        </Tr>
        <Tr>
          <Th>offsetY</Th>
          <Td>
            <OffsetPicker
              value={timelineClip.clip.offsetY}
              onChange={onOffsetYChange}
              extraOptions={['top', 'center', 'bottom']}
            />
          </Td>
        </Tr>
        <Tr>
          <Td colSpan={2}>
            <Group>
              <Button disabled={timelineClip.isFirst} onClick={onMoveLeft}>
                Move &lt;
              </Button>
              <Button disabled={timelineClip.isLast} onClick={onMoveRight}>
                Move &gt;
              </Button>
            </Group>
          </Td>
        </Tr>
      </Table.Tbody>
    </Table>
  );
};

// src/routes/timeline/video_clip_details.svelte
<script lang="ts">
  import type { VideoTimelineClip } from '$lib/video/video_timeline.svelte';
  import { toMinutesString } from '$lib/time_utils.js';
  import OffsetPicker from './offset_picker.svelte';
  import type { Manifest } from '$lib/manifest/manifest.svelte';

  export let manifest: Manifest;
  export let timelineClip: VideoTimelineClip;
  export let playheadTime: number;

  $: canMoveLeft = timelineClip.index > 0;
  $: canMoveRight = !timelineClip.isLast;

  function handleRateChange(e: Event & { currentTarget: HTMLInputElement }) {
    manifest.videoTrack.getClip(timelineClip.videoId).rate = Number(
      e.currentTarget.value,
    );
  }

  function handleOffsetXChange(offsetX: number | string | undefined) {
    manifest.videoTrack.getClip(timelineClip.videoId).offsetX = offsetX;
  }

  function handleOffsetYChange(offsetY: number | string | undefined) {
    manifest.videoTrack.getClip(timelineClip.videoId).offsetY = offsetY;
  }

  function handleCustomDurationChange(
    e: Event & { currentTarget: HTMLInputElement },
  ) {
    manifest.videoTrack.getClip(timelineClip.videoId).duration = Number(
      e.currentTarget.value,
    );
  }

  function handleTrimEndChange(e: Event & { currentTarget: HTMLInputElement }) {
    manifest.videoTrack.getClip(timelineClip.videoId).trimEnd = Number(
      e.currentTarget.value,
    );
  }

  function handleMoveLeft() {
    manifest.videoTrack.moveLeft(timelineClip.videoId);
  }

  function handleMoveRight() {
    manifest.videoTrack.moveRight(timelineClip.videoId);
  }
</script>

<div>
  <table>
    <tbody>
      <tr>
        <th class="head">id</th>
        <td class="cell">{timelineClip.videoId}</td>
      </tr>
      <tr>
        <th class="head">index</th>
        <td class="cell">{timelineClip.index}</td>
      </tr>
      <tr>
        <th class="head">last</th>
        <td class="cell">{timelineClip.isLast}</td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
      <tr>
        <th class="head">start</th>
        <td class="cell">{toMinutesString(timelineClip.start)}</td>
      </tr>
      <tr>
        <th class="head">end</th>
        <td class="cell">{toMinutesString(timelineClip.end)}</td>
      </tr>
      <tr>
        <th class="head">custom duration</th>
        <td class="cell">
          <input
            type="number"
            value={timelineClip.customDuration}
            on:change={handleCustomDurationChange}
          />
        </td>
      </tr>
      <tr>
        <th class="head">duration</th>
        <td class="cell">{toMinutesString(timelineClip.duration)}</td>
      </tr>
      <tr>
        <th class="head">rated duration</th>
        <td class="cell">{toMinutesString(timelineClip.ratedDuration)}</td>
      </tr>
      <tr>
        <th class="head">rate</th>
        <td class="cell">
          <input
            type="number"
            value={timelineClip.rate}
            min={0.1}
            step={0.1}
            max={10}
            on:change={handleRateChange}
          />
        </td>
      </tr>
      <tr>
        <th class="head">file duration</th>
        <td class="cell">{toMinutesString(timelineClip.fileDuration)}</td>
      </tr>
      <tr>
        <th class="head">trimmed duration</th>
        <td class="cell">{toMinutesString(timelineClip.trimmedDuration)}</td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
      <tr>
        <th class="head">time left</th>
        <td class="cell">
          {playheadTime > timelineClip.end || playheadTime < timelineClip.start
            ? '-'
            : toMinutesString(timelineClip.end - playheadTime, true)}
        </td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
      <tr>
        <th class="head">trim end</th>
        <td class="cell">
          <input
            type="number"
            on:change={handleTrimEndChange}
            value={timelineClip.clip.trimEnd}
          />
        </td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
      <tr>
        <th class="head">offsetX</th>
        <td class="cell">
          <OffsetPicker
            extraOptions={['left', 'center', 'right']}
            value={timelineClip.clip.offsetX}
            onChange={handleOffsetXChange}
          />
        </td>
      </tr>
      <tr>
        <th class="head">offsetY</th>
        <td class="cell">
          <OffsetPicker
            extraOptions={['top', 'center', 'bottom']}
            value={timelineClip.clip.offsetY}
            onChange={handleOffsetYChange}
          />
        </td>
      </tr>
      <tr class="divider">
        <td colspan="2"></td>
      </tr>
    </tbody>
  </table>
  <button disabled={!canMoveLeft} on:click={handleMoveLeft}>Move &lt;</button>
  <button disabled={!canMoveRight} on:click={handleMoveRight}>Move &gt;</button>
</div>

<style>
  .head {
    text-align: right;
  }

  .cell {
    text-align: left;
  }

  .divider {
    padding: 0;
    height: 3px;
    background: #eee;
    border: 0;
  }
</style>
