// src/routes/timeline/playhead_track.svelte
<script lang='ts'>
  export let time: number;
  export let maxDuration: number;
  export let onSeek: (seekedToTime: number) => void;

  $: playheadX = time / maxDuration * 100;

  function handleTrackClick(e: MouseEvent) {
    const x = e.offsetX;
    const position = x / e.target.clientWidth;
    const seekedToTime = maxDuration * position;
    onSeek?.(seekedToTime);
  }
</script>

<div class='track' on:click={handleTrackClick}>
  <div class='playhead' style='left: {playheadX}%'></div>
</div>

<style>
  .track {
    height: 20px;
    width: 100%;
    background: green;
    position: relative;
  }

  .playhead {
    position: absolute;
    height: 100%;
    width: 3px;
    background: yellow;
  }
</style>

// src2/pages/timeline/playhead_track/playhead_track.tsx
import classes from './playhead_track.module.css';

export const PlayheadTrack = ({
  time,
  maxDuration,
  onSeek,
}: {
  time: number;
  maxDuration: number;
  onSeek: (seekedToTime: number) => void;
}) => {
  const playheadX = (time / maxDuration) * 100;

  const onClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const x = e.nativeEvent.offsetX;
    const position = x / (e.target as HTMLDivElement).clientWidth;
    const seekedToTime = maxDuration * position;
    onSeek?.(seekedToTime);
  };

  return (
    <div className={classes.root} onClick={onClick}>
      <div className={classes.playhead} style={{ left: `${playheadX}%` }}></div>
    </div>
  );
};
