// src/features/renderer/renderer_surface.tsx
import type { EffectsState } from '../effects/effects_store';
import { useRenderLoop } from '../use_render_loop';
import type { RenderablePlayer } from '../video_player/renderable_player';
import { Renderer } from './renderer';
import React from 'react';

export const RendererSurface = ({
  width,
  height,
  player,
  offset,
  effectsState,
  onClick,
}: {
  width: number;
  height: number;
  player: RenderablePlayer;
  offset?: {
    offsetX: number | string | undefined;
    offsetY: number | string | undefined;
  };
  effectsState?: EffectsState;
  onClick?: () => void;
}) => {
  const { subscribeToTick } = useRenderLoop();

  const rendererRef = React.useRef<Renderer | null>(null);
  const canvasRef = React.useRef<HTMLCanvasElement | null>(null);

  React.useEffect(() => {
    if (canvasRef.current == null) {
      return;
    }
    rendererRef.current = Renderer.createFromCanvas(canvasRef.current);
  }, []);

  React.useEffect(
    () =>
      subscribeToTick(({ lastTime }) => {
        player.updateFrame();

        const renderSource = player.createRenderSource();

        rendererRef.current?.updateFrame({
          renderSource,
          lastTime,
          offset,
          effectsState,
        });
      }),
    [rendererRef.current, player, offset, effectsState],
  );

  return (
    <canvas
      ref={canvasRef}
      width={width}
      height={height}
      onClick={onClick}
    ></canvas>
  );
};

// src/lib/renderer/renderer_surface.svelte
<script lang="ts">
  import { getContext, onMount } from 'svelte';
  import { Renderer } from '$lib/renderer/renderer';
  import { RenderLoop } from '$lib/render_loop';
  import { RenderLoopKey } from '$lib/di';
  import type { EffectsMap } from './effects_map.svelte';
  import type { AudioInfo } from '$lib/audio/audio_analyser';
  import type { RenderablePlayer } from '$lib/video/renderable_player';

  const renderLoop = getContext<RenderLoop>(RenderLoopKey);
  // renderLoop.start();

  export let player: RenderablePlayer;
  export let effects: EffectsMap | undefined = undefined;
  export let audioInfo: AudioInfo | undefined = undefined;
  export let offset:
    | {
        offsetX: number | string | undefined;
        offsetY: number | string | undefined;
      }
    | undefined = undefined;
  export let nextPlayer: RenderablePlayer | undefined = undefined;
  export let width: number = 800;
  export let height: number = 800;
  export let onClick: (() => void) | undefined = undefined;

  let canvasElement: HTMLCanvasElement;
  let renderer: Renderer;

  onMount(() => {
    renderer = Renderer.createFromCanvas(canvasElement);

    renderLoop.tick.addListener(({ lastTime }) => {
      player.updateFrame();
      // nextPlayer?.updateFrame();

      const renderSource = player.createRenderSource();

      // TODO: compositor
      renderer.updateFrame(
        { renderSource, effects, offset, lastTime, audioInfo },
        undefined,
      );
    });
  });
</script>

<canvas bind:this={canvasElement} {width} {height} onclick={onClick}></canvas>
