// src/pages/assets/preview_base_item.tsx
import type { EffectsState } from '../../features/effects/effects_store';
import { useRenderLoop } from '../../features/use_render_loop';
import { useVideoPreviewFactory } from '../../features/video_preview_factory/use_video_preview_factory';
import type { VideoPreview } from '../../features/video_preview_factory/video_preview';
import type { RenderLoopTickEvent } from '../../lib/render_loop';
import classes from './preview_base_item.module.css';
import React from 'react';

export const PreviewBaseItem = ({
  videoPath,
  videoTrimmedDuration,
  effectsState,
  headerLeft,
  headerRight,
  footerLeft,
  footerRight,
  controls,
}: {
  videoPath: string;
  videoTrimmedDuration?: number;
  effectsState?: EffectsState;
  headerLeft?: React.ReactNode;
  headerRight?: React.ReactNode;
  footerLeft?: React.ReactNode;
  footerRight?: React.ReactNode;
  controls?: React.ReactNode;
}) => {
  const { subscribeToTick } = useRenderLoop();
  const { videoPreviewFactory } = useVideoPreviewFactory();

  const videoPreviewRef = React.useRef<VideoPreview | undefined>(undefined);

  const canvasContainerRef = React.useRef<HTMLDivElement>(null);

  const load = () => {
    const abortController = new AbortController();
    videoPreviewFactory
      .create(videoPath, {
        trimmedDuration: videoTrimmedDuration,
      })
      .then((videoPreview) => {
        if (abortController.signal.aborted) {
          return;
        }

        const canvas = videoPreview.renderer.canvas;
        canvasContainerRef.current?.appendChild(canvas);
        videoPreviewRef.current = videoPreview;
        videoPreviewRef.current.update({ lastTime: 0, effectsState });
      });

    return () => {
      abortController.abort();
    };
  };

  React.useEffect(() => load(), []);

  const onTick = ({ lastTime }: RenderLoopTickEvent) => {
    if (videoPreviewRef.current?.player.isPlaying) {
      videoPreviewRef.current.update({ lastTime, effectsState });
    }
  };

  React.useEffect(() => {
    videoPreviewRef.current?.update({ lastTime: 0, effectsState });
  }, [effectsState]);

  React.useEffect(() => subscribeToTick(onTick), []);

  const onCanvasClick = () => {
    videoPreviewRef.current?.togglePlay();
  };

  return (
    <div className={classes.container}>
      <div
        ref={canvasContainerRef}
        className={classes.canvas}
        onClick={onCanvasClick}
      ></div>
      <div className={classes.header}>
        <div>{headerLeft}</div>
        <div>{headerRight}</div>
      </div>
      <div className={classes.footer}>
        <div>{footerLeft}</div>
        <div>{footerRight}</div>
      </div>
      <div className={classes.controls}>{controls}</div>
    </div>
  );
};

// src/routes/preview/preview_base_item.svelte
<script lang="ts">
  import { getContext, onMount, type Snippet } from 'svelte';
  import type {
    VideoPreview,
    VideoPreviewFactory,
  } from '$lib/video/video_preview_factory';
  import { RenderLoopKey, VideoPreviewFactoryKey } from '$lib/di';
  import type { RenderLoop } from '$lib/render_loop';
  import type { EffectsMap } from '$lib/renderer/effects_map.svelte';

  const renderLoop = getContext<RenderLoop>(RenderLoopKey);
  const videoPreviewFactory = getContext<VideoPreviewFactory>(
    VideoPreviewFactoryKey,
  );

  let canvasContainerElement: HTMLDivElement;

  let {
    controls,
    videoPath,
    videoTrimmedDuration,
    effects,
    videoPreview,
    headerLeft,
    headerRight,
    footerLeft,
    footerRight,
  }: {
    controls?: Snippet;
    videoPath: string;
    videoTrimmedDuration?: number;
    effects?: EffectsMap;
    videoPreview?: VideoPreview | undefined;
    headerLeft?: string;
    headerRight?: string;
    footerLeft?: string;
    footerRight?: string;
  } = $props();

  onMount(async () => {
    videoPreview = await videoPreviewFactory.create(videoPath, {
      trimmedDuration: videoTrimmedDuration,
    });

    renderLoop.tick.addListener(() => {
      if (videoPreview?.player.isPlaying) {
        videoPreview?.update({ effects });
      }
    });
  });

  $effect(() => {
    if (videoPreview && canvasContainerElement) {
      canvasContainerElement.appendChild(videoPreview.renderer.canvas);
    }
  });

  $effect(() => {
    if (videoPreview && effects) {
      videoPreview.update({ effects });
    }
  });

  function handleCanvasClick() {
    videoPreview?.togglePlay();
  }
</script>

<div class="container">
  <div bind:this={canvasContainerElement} onclick={handleCanvasClick}></div>
  <div class="header">
    <div>{headerLeft}</div>
    <div>{headerRight}</div>
  </div>
  <div class="footer">
    <div>{footerLeft}</div>
    <div>{footerRight}</div>
  </div>
  <div>
    {@render controls?.()}
  </div>
</div>

<style>
  .container {
    width: 200px;
    height: 200px;
    background: #a1a1a1;
    display: inline-block;
    margin: 5px;
    margin-bottom: 50px;
    position: relative;
  }

  .header,
  .footer {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 20px;
    padding: 4px;
    display: flex;
    justify-content: space-between;
    font: 10px sans-serif;
    color: #eee;
  }

  .footer {
    bottom: 0;
    top: auto;
  }
</style>
