// src/pages/assets/unimported_item.tsx
import type { VideoFileAsset } from '../../features/assets/assets_controller';
import { useVideoResolver } from '../../features/video_resolver/use_video_resolver';
import { isImage } from '../../lib/image_utils';
import { toMinutesString } from '../../lib/time_utils';
import { PreviewBaseItem } from './preview_base_item';
import { Button } from '@mantine/core';
import React from 'react';

export const UnimportedItem = ({
  videoFileAsset,
  onImport,
  onDelete,
}: {
  videoFileAsset: VideoFileAsset;
  onImport: () => void;
  onDelete: () => void;
}) => {
  const { videoResolver, videoResolverSnap } = useVideoResolver();

  const duration = videoResolverSnap.getDuration(videoFileAsset.name);

  React.useEffect(() => {
    if (!isImage(videoFileAsset.name)) {
      videoResolver.loadMetadataOne({
        videoId: videoFileAsset.name,
        videoPath: videoFileAsset.path,
      });
    }
  }, [videoFileAsset, videoResolver]);

  const controls = (
    <>
      <Button onClick={onImport} size="compact-xs">
        Import
      </Button>
      <Button onClick={onDelete} size="compact-xs" color="red">
        Delete
      </Button>
    </>
  );

  return (
    <PreviewBaseItem
      videoPath={videoFileAsset.path}
      headerLeft={videoFileAsset.name}
      headerRight={toMinutesString(duration)}
      controls={controls}
    />
  );
};

// src/routes/preview/unimported_item.svelte
<script lang="ts">
  import { toMinutesString } from '$lib/time_utils';
  import { getContext, onMount } from 'svelte';
  import { VideoResolverKey } from '$lib/di';
  import type { SourceVideoFile } from '$lib/projects/projects_controller';
  import { VideoResolver } from '$lib/video/video_resolver';
  import type { VideoMetadata } from '$lib/video/video_resolver';
  import PreviewBaseItem from './preview_base_item.svelte';
  import { isImage } from '$lib/image_utils';

  const videoResolver = getContext<VideoResolver>(VideoResolverKey);

  export let sourceVideoFile: SourceVideoFile;
  export let onImport: (sourceVideoFile: SourceVideoFile) => void;

  let duration: number;

  onMount(async () => {
    if (isImage(sourceVideoFile.name)) {
      duration = 0;
    } else {
      duration = (
        await videoResolver.loadMetadataOne({
          videoId: sourceVideoFile.name,
          videoPath: sourceVideoFile.path,
        })
      ).duration;
    }
  });

  function handleImport() {
    onImport(sourceVideoFile);
  }
</script>

<PreviewBaseItem
  videoPath={sourceVideoFile.path}
  headerLeft={sourceVideoFile.name}
  headerRight={toMinutesString(duration)}
>
  {#snippet controls()}
    <button on:click={handleImport}>import</button>
  {/snippet}
</PreviewBaseItem>
