// src2/pages/preview/unimported_item.tsx
import { toMinutesString } from '../../lib/time_utils';
import type { SourceVideoFile } from '../../features/projects/projects_controller';
import { PreviewBaseItem } from './preview_base_item';
import { useVideoResolver } from '../../features/video_resolver/use_video_resolver';
import React from 'react';
import { isImage } from '../../lib/image_utils';
import { Button } from '@mantine/core';

export const UnimportedItem = ({
  sourceVideoFile,
  onImport,
}: {
  sourceVideoFile: SourceVideoFile;
  onImport: () => void;
}) => {
  const { videoResolver, videoResolverSnap } = useVideoResolver();

  const duration = videoResolverSnap.getDuration(sourceVideoFile.name);

  React.useEffect(() => {
    if (!isImage(sourceVideoFile.name)) {
      videoResolver.loadMetadataOne({
        videoId: sourceVideoFile.name,
        videoPath: sourceVideoFile.path,
      });
    }
  }, [sourceVideoFile, videoResolver]);

  const controls = (
    <Button onClick={onImport} size="compact-xs">
      Import
    </Button>
  );

  return (
    <PreviewBaseItem
      videoPath={sourceVideoFile.path}
      headerLeft={sourceVideoFile.name}
      headerRight={toMinutesString(duration)}
      controls={controls}
    />
  );
};

// src/routes/preview/unimported_item.svelte
<script lang="ts">
  import { toMinutesString } from '$lib/time_utils';
  import { getContext, onMount } from 'svelte';
  import { VideoResolverKey } from '$lib/di';
  import type { SourceVideoFile } from '$lib/projects/projects_controller';
  import { VideoResolver } from '$lib/video/video_resolver';
  import type { VideoMetadata } from '$lib/video/video_resolver';
  import PreviewBaseItem from './preview_base_item.svelte';
  import { isImage } from '$lib/image_utils';

  const videoResolver = getContext<VideoResolver>(VideoResolverKey);

  export let sourceVideoFile: SourceVideoFile;
  export let onImport: (sourceVideoFile: SourceVideoFile) => void;

  let duration: number;

  onMount(async () => {
    if (isImage(sourceVideoFile.name)) {
      duration = 0;
    } else {
      duration = (
        await videoResolver.loadMetadataOne({
          videoId: sourceVideoFile.name,
          videoPath: sourceVideoFile.path,
        })
      ).duration;
    }
  });

  function handleImport() {
    onImport(sourceVideoFile);
  }
</script>

<PreviewBaseItem
  videoPath={sourceVideoFile.path}
  headerLeft={sourceVideoFile.name}
  headerRight={toMinutesString(duration)}
>
  {#snippet controls()}
    <button on:click={handleImport}>import</button>
  {/snippet}
</PreviewBaseItem>
